### ISSUE TITLE
Allow global round and global phases along with player turns

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#105]
Right now, OCTGN only supports player turns, i.e. one player does something, then another one does etc. But in many card games, there is also a global turn, where the phase of the game changes for each player at the same time, and they then alternate taking turns within that phase. Two example to understand what I mean.

In Doomtown, you have 1 global round, which consists of 4 global phases during each phase players either alternate turns until they both pass, or they play simulataneously.

So in the gambling phase, players simulataneously make a poker hand and reveal it, then compare ranks and get some rewards. 

In the High Noon phase, starting with the player who won in the gambling phase, they take alternate turns until they both pass

One game round is over after both players have passed in turn during High Noon and the next phase (Nighfall) has been completed as well. Then a next game round starts at the gambling phase.

Very similarly in DuneCCG, but instead of players alternating many turns during the main phase, they only take one turn each.

At the moment I've dealing with this via python, but it's suboptimal imho (i.e. using shared counters to mark phases). The ability to have the function built-in the game where the player can swap the global round and phases, and have various things triggered by it, or allow scripts to check for it would be very useful.

**Comment by brine** [comment]
game phases have been implemented
