### ISSUE TITLE
OCTGN crashes when loading a deck with a note if a notes font is defined

### ISSUE THREAD

**Issue by Blackmoor** [octgn/OCTGN#1087]
An unexpected error occurred.....

definition.xml code that crashes ...

```xml
  <fonts>
        <font src="Resources/dax.ttf" size="12" target="context" />
	<font src="Resources/dax.ttf" size="12" target="chat" />
	<font src="Resources/dax.ttf" size="12" target="notes" />
	<font src="Resources/dax.ttf" size="12" target="deckeditor" />
  </fonts>
```

Remove the notes line and it all works. The font works fine in the other 3 locations (context, chat and deck editor.)

**Comment by kellyelton** [comment]
This should be fixed by #b02d1f2b9e120ce63f4c16ef954017164c979485
