### ISSUE TITLE
Card flip not always propagating to other players

### ISSUE THREAD

**Issue by Blackmoor** [octgn/OCTGN#1088]
This looks like a new bug in the current release. Sometimes a card flip operation only updates the card image for the player performing the operation, the other players still see a facedown card, however if they hover over that card they do get the full size image (faceup).

**Comment by brine** [comment]
I'm like 90% sure we fixed this, it was some dumb shit relating to the CPU's internal clock or something.  More relevant than it sounds, I swear.
