### ISSUE TITLE
Moving markers in python now gives a warning

### ISSUE THREAD

**Issue by Blackmoor** [octgn/OCTGN#1201]
The GUI allows a user to pick up and drag markers from one card to another.
I have routines in python that emulate the same thing (subtract the markers from one card and add them onto the other card). If the destination card is not controlled by me, the new release issues a warning (Player Can't set markers on Card because they don't control it). Since it is allowed in the GUI, I would expect it to be allowed in python.
Can the warning be removed?
If not - what is the recommended way to move markers in python when the src and dst cards are controlled by different players?

**Comment by brine** [comment]
still an issue?
