### ISSUE TITLE
Mute built in drag notifications

### ISSUE THREAD

**Issue by Lynesth** [octgn/OCTGN#1266]
Hey there.

Maybe I just didn't see it (though I spent a lot of time looking for this), so is there a way to mute the built in notifications that pop when a player drag a card to a hand/pile/table ?

You know, the one that goes like "Player moves Card to Table".

**Comment by Lynesth** [comment]
I guess I'll just bump this one since it's the question I was about to ask again :)

**Comment by brine** [comment]
you can mute the "{} reorders {}" message by putting the `ordered="False"` attribute into the game's `<group>` or `<hand>` tag, but I dont think theres a way to mute the "moves" notification

**Comment by Lynesth** [comment]
Thank you for your answer.
Could we maybe add a way to mute everything at once ?
Maybe as an optionnal property in the game definition, or a function we could call during **OnTableLoad** ?

**Comment by brine** [comment]
This should have been closed when we added event overrides.  You can use the OverrideCardsMoved event to implement a custom version of this action through python, including the notification message.
