### ISSUE TITLE
Add ability to turn off phase management buttons in the GUI

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1278]
I would like to have the ability to script Turn Management but not give the players to manage Turns via the pause/play buttons in the GUI.

The reasoning is that in my game, I have game phases that happen during a game round (Turn) and if they push the button, on purpose or accident, it can muck things up.

Just a setting in the definition.xml to make it configurable would work great.

**Comment by brine** [comment]
combination of the phase bar and pass turn overrides should handle this
