### ISSUE TITLE
card.alternate can be inconsistent between players depending on who loaded the cards into the game

### ISSUE THREAD

**Issue by Blackmoor** [octgn/OCTGN#1284]
Player 1 loads a deck (into the shared piles). There are 6 copies of certain card in the loaded deck. Player 1 moves 2 of these (same named) cards onto the table.

Player 1 flips over one of these 2 cards to its alternate side "B"
If player 1 queries the card.alternate state of the cards on the table it correctly shows the flipped card has card.alternate == 'B' and the other card as card.alternate==""

If, instead, player 2 moves the 2 cards to the table and flips over 1 of them BOTH cards when queried show alternate=='B'

I have done a lot of testing of permutations (with 2 players) and it always works for the player who loaded the cards and goes wrong for the player who didn't load the deck.

Note: This is only an issue if the 2 cards are the same named (i.e. GUID) card.

**Comment by brine** [comment]
skimming through some old tickets -- I believe this the same bug as #1677 , which is fixed in #1699.
