### ISSUE TITLE
[Wine] Socket errors related to frequent disconnects?

### ISSUE THREAD

**Issue by eah13** [octgn/OCTGN#1302]
This should get tagged as Wine.

Running wine on Ubuntu 12.04, OCTGN often disconnects me on an otherwise spotless internet connection.  I'm suspicious it has something to do with encryption or sockets.  The fatal disconnects include the in-chat error message "You must shake hands. No one likes and anit-social connection".  I'm currently at 50% disconnects, maybe 20% of which lock me out.  There doesn't seem to be any in-game pattern to when these happen.  It's difficult to know why other players disconnect when they do but I imagine it's related.

This from the console, possibly related?

```
WARN   3.1.143.328 [1] Octgn.Networking.ClientSocket [(null)] - Send  System.NullReferenceException: Object reference not set to an instance of an object.    at Octgn.Core.Networking.SocketBase.Send(Byte[] data) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn.Core\Networking\SocketBase.cs:line 119
```

A second type of disconnect leaves me in the game, able to chat, but unable to perform any game actions.  I've talked with several other players who were experiencing this state.

This from the console when this happened most recently:

```
WARN   3.1.143.328 [4] Octgn.Networking.ClientSocket [(null)] - EndReceive
 System.Net.Sockets.SocketException (0x80004005): Not enough memory
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Octgn.Core.Networking.SocketBase.EndReceive(IAsyncResult res) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn.Core\Networking\SocketBase.cs:line 160
fixme:advapi:LsaOpenPolicy ((null),0x574d93c,0x00000800,0x574d914) stub
fixme:advapi:LsaClose (0xcafe) stub
ERROR  3.1.143.328 [4] Octgn.Networking.ClientSocket [(null)] - Disconnect Event 96.31.76.45:10776
```

This is running wine 1.6.1, which is what apt installs when I tell it to install wine 1.5.

Hope that helps.  The non-Microsoft world is counting on you.

**Comment by finnbar** [comment]
I've not got much to add here, but I've experienced the same problem a few times. I've got a log for my most recent disconnect here: https://gist.github.com/finnbar/7ea80f5e883387323ded

I find that it takes a few games for the disconnect to appear (maybe 3 or 4 connections (5 or 6 games - I tend to play both sides in Netrunner)), and it usually consists of an "antisocial connection" error - although, in this case, I was given an "antisocial connection" error and then a new error ("received too many hellos" or something like that - as if the "hello" from the "antisocial connection" was just delayed).

I'm running OCTGN in a 32-bit prefix set up according to the Wiki. I'm running it on a 64-bit laptop with Elementary Freya Beta 2 (built on Ubuntu 14.04) and 8GB of RAM (full specs are in the same gist as above). So it may be related to the amount of RAM Wine gives it (being 32bit, it's still limited to 2GB no matter what (I think)), but it seems that there's been a lot of testing into that already.

I hope I've provided at least a little something that you might find useful, although it seems like most of what I'm saying has already been worked out.

(also, OCTGN is pretty amazing to say the least, so thank you for that!)
