### ISSUE TITLE
Stop working when application launch

### ISSUE THREAD

**Issue by wennx96** [octgn/OCTGN#1313]
INFO  2014-08-21 15:30:16,886 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll
 INFO  2014-08-21 15:30:16,925 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll
 INFO  2014-08-21 15:30:16,932 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
 INFO  2014-08-21 15:30:16,937 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll
 INFO  2014-08-21 15:30:16,945 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
 INFO  2014-08-21 15:30:17,025 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
 INFO  2014-08-21 15:30:17,027 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
 INFO  2014-08-21 15:30:17,124 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: Octgn.Site.Api, Version=1.0.1.69, Culture=neutral, PublicKeyToken=null - E:\Wennx\Documents\OCTGN\OCTGN\Octgn.Site.Api.dll
 INFO  2014-08-21 15:30:17,200 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: Common.Logging, Version=2.1.2.0, Culture=neutral, PublicKeyToken=af08829b84f0328e - E:\Wennx\Documents\OCTGN\OCTGN\Common.Logging.dll
 INFO  2014-08-21 15:30:17,219 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: Skylabs.Lobby, Version=3.1.149.334, Culture=neutral, PublicKeyToken=null - E:\Wennx\Documents\OCTGN\OCTGN\Skylabs.Lobby.dll
 INFO  2014-08-21 15:30:17,221 3.1.149.334 [1] Octgn.Program [(null)] - Constructng Program
 INFO  2014-08-21 15:30:17,223 3.1.149.334 [1] Octgn.Program [(null)] - Setting SSL Validation Helper
 INFO  2014-08-21 15:30:17,227 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll
 INFO  2014-08-21 15:30:17,245 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed - E:\Wennx\Documents\OCTGN\OCTGN\Newtonsoft.Json.dll
 INFO  2014-08-21 15:30:17,319 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll
 INFO  2014-08-21 15:30:17,336 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.IO.Abstractions, Version=1.4.0.69, Culture=neutral, PublicKeyToken=d480b5b72fb413da - E:\Wennx\Documents\OCTGN\OCTGN\System.IO.Abstractions.dll
 INFO  2014-08-21 15:30:17,340 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path WorkingDirectory = E:\Wennx\Documents\OCTGN\OCTGN\OCTGN.exe
 INFO  2014-08-21 15:30:17,341 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path BasePath = E:\Wennx\Documents\OCTGN\OCTGN\
 INFO  2014-08-21 15:30:17,341 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path UserDirectory = C:\Users\Wennx\Documents\Octgn
 INFO  2014-08-21 15:30:17,342 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path PluginPath = C:\Users\Wennx\Documents\Octgn\Plugins
 INFO  2014-08-21 15:30:17,342 3.1.149.334 [1] Octgn.Utils.SSLValidationHelper [(null)] - Bypass SSL certificate validation set to: False
 INFO  2014-08-21 15:30:17,342 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path DataDirectory = C:\Users\Wennx\Documents\Octgn
 INFO  2014-08-21 15:30:17,343 3.1.149.334 [1] Octgn.Program [(null)] - Setting api path
 INFO  2014-08-21 15:30:17,343 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path DatabasePath = C:\Users\Wennx\Documents\Octgn\GameDatabase
 INFO  2014-08-21 15:30:17,344 3.1.149.334 [1] Octgn.AppConfig [(null)] - Setting AppConfig
 INFO  2014-08-21 15:30:17,344 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path ImageDatabasePath = C:\Users\Wennx\Documents\Octgn\ImageDatabase
 INFO  2014-08-21 15:30:17,344 3.1.149.334 [1] Octgn.AppConfig [(null)] - Set AppConfig
 INFO  2014-08-21 15:30:17,344 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path ConfigDirectory = C:\Users\Wennx\Documents\Octgn\Config
 INFO  2014-08-21 15:30:17,345 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path FeedListPath = C:\Users\Wennx\Documents\Octgn\Config\feeds.txt
 INFO  2014-08-21 15:30:17,345 3.1.149.334 [1] Octgn.Program [(null)] - Setting temp main window
 INFO  2014-08-21 15:30:17,346 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path LocalFeedPath = C:\Users\Wennx\Documents\Octgn\LocalFeed
 INFO  2014-08-21 15:30:17,346 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path MainOctgnFeed = https://www.myget.org/F/octgngames/
 INFO  2014-08-21 15:30:17,346 3.1.149.334 [1] Octgn.Program [(null)] - Checking if admin
 INFO  2014-08-21 15:30:17,347 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path DeckPath = C:\Users\Wennx\Documents\Octgn\Decks
 INFO  2014-08-21 15:30:17,347 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path LogsPath = E:\Wennx\Documents\OCTGN\OCTGN\Logs
 INFO  2014-08-21 15:30:17,348 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path CurrentLogPath = E:\Wennx\Documents\OCTGN\OCTGN\Logs\log.txt
 INFO  2014-08-21 15:30:17,348 3.1.149.334 [1] Octgn.Program [(null)] - Check if running on network drive
 INFO  2014-08-21 15:30:17,348 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path PreviousLogPath = E:\Wennx\Documents\OCTGN\OCTGN\Logs\log.txt.1
 INFO  2014-08-21 15:30:17,349 3.1.149.334 [1] Octgn.Program [(null)] - Creating Lobby Client
 INFO  2014-08-21 15:30:17,349 3.1.149.334 [7] Octgn.Library.Paths [(null)] - Path GraveyardPath = C:\Users\Wennx\Documents\Octgn\Garbage\f9378b17-5650-45ef-82e2-6ed4be903c33
 INFO  2014-08-21 15:30:17,351 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: agsXMPP, Version=1.3.0.0, Culture=neutral, PublicKeyToken=ff839b81f1debe86 - E:\Wennx\Documents\OCTGN\OCTGN\agsXMPP.dll
 INFO  2014-08-21 15:30:17,406 3.1.149.334 [1] Octgn.Program [(null)] - Creating Game Message Dispatcher
 INFO  2014-08-21 15:30:17,408 3.1.149.334 [1] Octgn.Program [(null)] - Registering versioned stuff
 INFO  2014-08-21 15:30:17,408 3.1.149.334 [1] Octgn.Program [(null)] - Setting Games Path
 INFO  2014-08-21 15:30:17,409 3.1.149.334 [1] Octgn.Program [(null)] - Finished Constructing Program
 INFO  2014-08-21 15:30:17,412 3.1.149.334 [1] Octgn.OctgnApp [(null)] - LOADED ASSEMBLY: System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll
 INFO  2014-08-21 15:30:17,414 3.1.149.334 [1] Octgn.Program [(null)] - Start
 INFO  2014-08-21 15:30:17,415 3.1.149.334 [1] Octgn.Program [(null)] - Decide to ask about wine

**Comment by Soul1355** [comment]
#1387 related?
