### ISSUE TITLE
Bundle plugins in with games

### ISSUE THREAD

**Issue by kellyelton** [octgn/OCTGN#1317]
Add the ability to bundle plugins in with games. On install, they unzip into the normal plugins folder instead of in the game directory.

Since we can't delete plugins while octgn is running, on start we should check to see if there is a deferred request to delete a plugin(Created when uninstalling a game) and delete it.

Seems to me that the only way to even tell if we need to delete the plugin is for the def to have some reference to the plugin dll, so we'll need a new element in the def. Of course this should go without saying, but this element needs to be optional.

```
<pluginFiles>
    <pluginFile src="/relateive/path/in/package"></pluginFile>
</pluginFiles>
```

**Comment by sIKE23** [comment]
I work on the Mage Wars Plugin and am will to make sure it gets migrated over

**Comment by brine** [comment]
should be closed as fixed

**Comment by brine** [comment]
maybe, is there something we haven't done yet from this?

**Comment by kellyelton** [comment]
Why was this closed, how was this implemented?

**Comment by brine** [comment]
The game installer copies the Plugins subfolder into OCTGNs plugins location
