### ISSUE TITLE
Allow specifed markers to show the numeral one

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1367]
With the change implemented from issue #113 there is an unplanned side effect for games that use makers as counters. For those game please add the ability to select if you wish to hide (default) the numeral one or display it.

So marker would gain the 'hideIfOnlyOne=true/false' as a configuration option

```xml
<markers>
	<marker id="c3de25bf-4845-4d2d-8a28-6c31ad12af46" name="Corrode" hideIfOnlyOne="False"	 />
	<marker id="c580e015-96ff-4b8c-8905-28688bcd70e8" name="Growth" />
</markers>
```

**Comment by brine** [comment]
This should probably be a reversion until a better implementation is figured out

**Comment by sIKE23** [comment]
Just so you are aware my game currently has 71 markers and it grows 4-10 each release.

**Comment by sIKE23** [comment]
Your #1 Kelly and or so my markers now say. Very happy camper!
