### ISSUE TITLE
Abiltiy to copy error message out of chat window

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1368]
It would be nice if players or developers could grab the errors messages out of the chat window to aid in troubleshooting the error.

**Comment by sIKE23** [comment]
Still unable to copy the error message...

![errors](https://cloud.githubusercontent.com/assets/5695175/7602377/a27b3944-f8e9-11e4-8dc7-e91b02d14844.jpg)

**Comment by kellyelton** [comment]
It works for sure I tried it multiple times

**Comment by kellyelton** [comment]
Ok. So I had made it work so that you could copy the ENTIRE error, not a sub section of it. I'm going to push up something that'll just let you do the whole thing though

**Comment by sIKE23** [comment]
I cant do either ....
