### ISSUE TITLE
Can't retrieve news feed

### ISSUE THREAD

**Issue by yamadaty** [octgn/OCTGN#1369]
Can't retrieve news feed and looks like login doesn't work since i don't see any games. Firewall, antivirus disabled. 

http://pastebin.com/YNmMWhyy

Please Help
Thanks

**Comment by Soul1355** [comment]
I'm going to assume this was at some point when our severs were down, as that is exactly what happens when they aren't available. if this is not the case, I apologize nobody got back to you. (and let us know)
