### ISSUE TITLE
OCTGN shuts down after sound error

### ISSUE THREAD

**Issue by SteveHouston** [octgn/OCTGN#1378]
This happens to me in Netrunner games too frequently.  1 in 6 games perhaps.  Please let me know if there is a fix on my end.  After a run sound effect is supposed to play, the program crashes.

![image](https://cloud.githubusercontent.com/assets/7469003/6198897/6205aab0-b3ee-11e4-9bc1-0643be608099.png)

**Comment by Gravecorp** [comment]
the sound file itself might be corrupt. uninstalling the game definition and then reinstalling might fix it.

**Comment by Soul1355** [comment]
is this still an issue or were you able to resolve it?
