### ISSUE TITLE
OCTGN won't install image packs with Crops folders

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1388]
We can't make crop image packs, OCTGN spits out errors when you try to add them

**Comment by Gravecorp** [comment]
I think thats because the install code hasnt been adjusted for it yet...

**Comment by Gravecorp** [comment]
It probably borks on trying to extract to an unexistant Crops directory.

**Comment by Gravecorp** [comment]
turns out it put the crops directory in what should be the card guid. the commit changes it back to what it should be.
