### ISSUE TITLE
louder sound effect when players join games

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1395]
http://help.octgn.net/support/discussions/topics/4000319658

The knocking sound when a player joins the game needs to be louder.  By comparison, the door closing sound when they leave the game is much louder

**Comment by Gravecorp** [comment]
I can upsample the sound

**Comment by kellyelton** [comment]
We could also think of using different sounds at this point if we wanted? Just a thought.

**Comment by Gravecorp** [comment]
Whatever works i added it as a stopgap measure in any case so its due a few change in any case.

**Comment by torrentails** [comment]
The systems are already in place for designers to use their own sounds when a player joins/leaves, how about adding a game def option to disable the default sounds?
