### ISSUE TITLE
make scriptVersion a mandatory attribute in o8build

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1418]
scriptVersion should be made a mandatory attribute when using o8build to compile game packages.  A gentle "reminder" to game devs that they need to set one so today's armageddon of bugged games doesn't happen again ;)

**Comment by Gravecorp** [comment]
https://github.com/octgn/OCTGN/blob/master/octgnFX/Octgn.Library/Schemas/Game.xsd#L584 change optional to required.
