### ISSUE TITLE
cannot get the card.model of a facedown card.

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#1426]
This seems to have been changed in the latest version of OCTGN and it broke significant functionality of my games, as I used the card.model to retrieve card scripts.

If a card is face down, in one's piles or the table, regardless of peek status, card.model will return None.

https://github.com/db0/Android-Netrunner-OCTGN/issues/603

This is a high impact regression bug for me.

**Comment by brine** [comment]
I just rolled back to the previous OCTGN release (from Jan. 20) to test this and the bug still happens there, are you sure this is new?

**Comment by brine** [comment]
actually, this is a regression between the 3.1.0.0 and 3.1.0.1 API versions, so changing scriptVersions is what caused this to happen, not the OCTGN update.  That said, this shouldn't be happening, so I'll have to look into why they behave differently between the versions

**Comment by db0** [comment]
OK, I guess I'll roll back to API 3.1.0.0 as an emergency fix until then

**Comment by brine** [comment]
its risky, you'll probably have to rollback your entire 3.1.0.1 upgrade

**Comment by db0** [comment]
I know, but it's a huge b0rk for my game. When do you think it'll be live for API 3.1.0.1?

**Comment by brine** [comment]
you could also add a temporary function to hotfix getting the model if you didnt want to roll-back:

```python
def getCardGUID(card):
    mute()
    c.isFaceUp = True
    cardGUID = card.model
    c.isFaceUp = False
    return cardGUID
    ```

I dunno how long till the fix comes out, theyve been overhauling the deployment system so I'm not even really sure where to make the pull requests to right now

**Comment by db0** [comment]
Will that work if I don't control the card?

**Comment by db0** [comment]
'''OnMoveCards''' is functionally identical between 3.1.0.0 and 3.1.0.1 no?

**Comment by brine** [comment]
itll work but you'll get those warning messges, probably not the best method but its a temporary patch till the proper fix pushes out.

They're not functionally the same, if you roll it back as-is then youre gonna get that event triggering off of script movements as well. So you'll need to use the isScriptMove parameter (which was converted to faceup in 3.1.0.1)

**Comment by brine** [comment]
should be good to go, double-check before you un-rollback tho

**Comment by db0** [comment]
I didn't see an OCTGN update though

**Comment by db0** [comment]
This looks to be live now. Can you confirm?

**Comment by brine** [comment]
yea  its good to go

**Comment by veyDer** [comment]
This problem is still happening in the current release. I've just run into it.
