### ISSUE TITLE
Need a function to determine whether someone is a player or a spectator

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1436]
isSpectator would work fine :)

**Comment by brine** [comment]
when would this take into effect? As far as I've tried, nothing in the python API is even able to recognize the spectator as a player.  Both Player(spectatorID), getPlayers(), and players will only return the active players.

**Comment by sIKE23** [comment]
The need for this is not as highly needed now. Using getPlayers() to weed out the spectators. And this little jewel lets my find the first player in the game:

str((sorted([x._id for x in getPlayers()])[0]))) 

It outputs the lowest player number and then you can write your code around it from there.....

**Comment by brine** [comment]
This will be reopened when a practical usage for exposing spectators to python happens.
