### ISSUE TITLE
Game Lobby Freezes (as well as OCTGN), when a player changes self from Player to Spectator

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1438]
Doesn't happen when you are in the Game Lobby by yourself, you can switch yourself back and forth, but once there are 2+ players in the Game Lobby when the change is made the Game Lobby and OCTGN freezes hard, and requires Task Manager + End Task. Reproducible every time. 

https://dl.dropboxusercontent.com/u/58842665/MageWars/Lobby.Bug.wmv

**Comment by brine** [comment]
there is an infinite loop going on in the background which causes OCTGN to lock up as soon as you click the spectate toggle.  Here's the error log that I got when this happened:
http://hastebin.com/caziveheli

**Comment by sIKE23** [comment]
This issue is in the same vein as #1310
