### ISSUE TITLE
[Significant] Random cards in hand unusable

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#1442]
Just got the new version and it seems to have broken the hand. Random cards in my hand will be unusable. This persists between resets and reshuffles/mulligans. I've made a video which shows this

http://www.twitch.tv/dbzer0/b/664039808

Makes games unplayable. Logs don't show any issues.

**Comment by db0** [comment]
Cards are still seen and affected by scripts (e.g. discard card at random can choose one of them, but card will still be unusable in the discard pile)

**Comment by db0** [comment]
Tried another of my games and I couldn't replicate this. Tried another deck and it worked fine. Tried a third deck and I saw it again. It seems limited to specific cards but always the same cards.

**Comment by db0** [comment]
It seems to be limited to specific sets. All cards in one set will behave this way.

**Comment by db0** [comment]
Once such a card is on the table, I can select it with drag-select, but cannot move or target it and it doesn't show the pop-up.

**Comment by db0** [comment]
I can replicate this consistently and have identified some affected sets. If you need more info lemme know.

**Comment by db0** [comment]
Confirmed it's affecting everyone.

**Comment by kellyelton** [comment]
Its rolled back one further. Please provide any specific info you can to replicatr

**Comment by kellyelton** [comment]
The updates added allowed clicking through transparency, I'm not sure why that would even affect you.

**Comment by kellyelton** [comment]
In going to need feedback or this will go back out again

**Comment by Soul1355** [comment]
what is the image format of the affected sets, and is it the same as unaffected sets?

**Comment by db0** [comment]
Cards are .png format. Want a sample?

**Comment by kellyelton** [comment]
Yeah anything you can provide to solve the problem would help.

**Comment by db0** [comment]
This is one of the cards where this is happening: https://drive.google.com/file/d/0B-gMiPlH3rBAcmhuWkpreHpSdWs/view?usp=sharing

**Comment by kellyelton** [comment]
Can you also send a picture of one that does work?

**Comment by brine** [comment]
Hop in chat it would make this hella easier

**Comment by db0** [comment]
You guys don't have a link to the chat anywhere anymore.

The ones that worked were all .jpg which don't support transparency. I didn't look too closely to see if there was a .png that worked.

**Comment by kellyelton** [comment]
So far I see your png is 8 bit, which might be part of it

**Comment by db0** [comment]
Dunno. That's the kind of images almost everyone who plays ANR uses.

**Comment by brine** [comment]
Its still irc.freenode.net #octgn, hasnt changed
