### ISSUE TITLE
Anchored cards can be "Move to"

### ISSUE THREAD

**Issue by Lynesth** [octgn/OCTGN#1450]
Hey there,

When a card is anchored on the table, it can still be moved using the "Move to" command in the right-click menu.
It can be troublesome if it's sent to the library for example because you can't draw by dragging anymore : the top card is anchored.

I guess that either the card should be unanchored before the move or the "Move to" command should be greyed out.

What do you think ?

Regards,

Lyn.

**Comment by brine** [comment]
Yeah it should get anchored, this is a bug
