### ISSUE TITLE
Can't retrieve card or card.name

### ISSUE THREAD

**Issue by Lynesth** [octgn/OCTGN#1451]
Hey there,

Third issue in a row, I know. I checked before posting though, and can't find anything related to this :
Whenever I do
``` notify("You draw a {}".format(card)) ```
or
``` notify("You draw a {}".format(card.name)) ```
or even 
``` notify(card.name) ```

I simply get a blank space where the name of the card should be. The same goes for whisper by the way.

I have to create a property with the name "name" for it to work correctly.
```
<card name="Zombie" id="b2df97eb-4fce-4eb0-80c5-309feca9e03a">
    <property name="name" value="Zombie" />
</card>
```

Is it the way it should be and I really missed it or am I doing something wrong here or what ?

Regards,

Lyn.

**Comment by brine** [comment]
Something must be happening in your def cuz this is working fine for me. Can you post the function youre trying to use this with?

**Comment by Lynesth** [comment]
It happens, for example, with this function here :
```python
def playCard(card):
	cc = int(card.cost)
	if cc > me.curMana:
		whisper("Not enough mana to play {}.".format(card))
```

Which is called like that using OnCardDoubleClick event :

```python
def checkDoubleClick(card, mouseButton, keys):
	mute()
	if card.controller == me:
		if card.group == me.hand:
			playCard(card)
```

I'll try a few more things to give you more informations.

**Comment by brine** [comment]
the card name is hardwired into the set definitions, where it reads `<card name="Zombie" id="xxxx">`.  It should always be made available to python, if it doesn't have visibility of the card then it should be displayed simply as "Card" in the chat notifications.

You shouldn't be using "name" as a custom property as its reserved by OCTGN for the above purpose.  In fact, o8build should be blocking you from using "name" as a custom property in the first place.

**Comment by brine** [comment]
can you change your checkDoubleClick function to this: 

```python
def checkDoubleClick(card, mouseButton, keys):
    mute()
    notify("TEST: {}~{}~{}".format(card, card.name, card.Name))
    if card.controller == me:
        if card.group == me.hand:
            playCard(card)
```
and let me know what it returns?

Try it with a bunch of different cards you have in the game.  Does the notify lines work for other functions in your game?

**Comment by Lynesth** [comment]
I tried as you ask, the result is the same, it outputs : ``` Test: ~~ ```

With the card I forced the custom property "name" on, it outputs the correct behavior : ``` Test: Zombie~Zombie~Zombie ``` the first one being underlined and showing the card on hover.

I can't get notify to print the card or the card name in any other function.

**Comment by db0** [comment]
Intead of using a onDoubleClick event, have you tried simply setting that
function as the default for the cardaction and seeing if it works that way?

**Comment by Lynesth** [comment]
Ok I found out where it came from.

I had this in my definition.xml under card : 
```xml
<property name="name" type="String" hidden="False" ignoreText="False" textKind="Free" />
```
o8build didn't raise any warning or error concerning this so I guess this is a bug :)

Thanks for you help !

**Comment by brine** [comment]
this isn't related to the specific issue, but as db0 suggested, you should be setting this as the default cardaction for the table instead of using the OnDoubleClick event.  OnDoubleClick is usually used to run scripts off cards you don't control.  If you only care about cards you control, then the default cardaction is a more efficient method of doing this.

**Comment by db0** [comment]
onDoubleClick works on cards you don't control?!

Mind. Blown!

**Comment by brine** [comment]
yea i thought thats why it was added in the first place.  It only triggers locally though

**Comment by db0** [comment]
yeah that makes sense.

**Comment by Lynesth** [comment]
Yeah, I was just trying some things out.
Thanks for the advice though. (Bumped an old issue btw, if you could take a look :p)

**Comment by db0** [comment]
Question, would the default action and the onDoubleClick even trigger at
the same time for cards you control? I assume they would.

**Comment by brine** [comment]
I think the default action triggers first cuz there's a bit of a delay in event hooks, not sure.  They both WILL trigger though

**Comment by kellyelton** [comment]
As a double side note, rnd(0,anything) doesn't do anything except generate a random number. It doesn't cause a delay, and also the size of the numbers in the rnd function don't create more/less of a delay.
