### ISSUE TITLE
Request : new event

### ISSUE THREAD

**Issue by Lynesth** [octgn/OCTGN#1452]
Just wondering if it'd be possible to get a **OnBeforeMoveCard** event with the same parameters as **OnMoveEvent** that fires right before the cards are actually moved and that could allow us to prevent the actual moving of the cards ?

Is it something that could be implemented ?
It may also be usefull for other events too, but this is the one I could currently make use of :)

Regards,

Lyn.

**Comment by brine** [comment]
you can use the onMoveCards event to "undo" the movement of cards by returning them to the previous location passed in the arguments.  This is the only practical way to do this via events, as the manual movement of cards occurs outside of the python layer and cannot be "blocked" by python or the event system

**Comment by Lynesth** [comment]
This is what I currently do, but I thought that it was making a lot a of work for "nothing". Having cards going back and forth, and all of this over the network, etc.
But the main reason is that even if it's fast enough to undo the changes, it still notifies the cards that were moved that way, hence my other request :)

Anyway, thanks for your answer.

Lyn.

**Comment by brine** [comment]
I highly recommend joining the IRC chatroom, we're usually there to help out with OCTGN game development and its a lot easier to bounce this kind of stuff back and forth

**Comment by brine** [comment]
closing this as the python engine doesn't really have the ability to interrupt these sorts of things.  The game events are more like an echo that gets triggered after an action happens, they don't have control over anything.
