### ISSUE TITLE
Both players have the same y position on a 2-sided table

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#146]
When using a two-sided table, player 1's position (0,0) is just below the separating line, so that the top of the card is exactly on top of the line. Unfortunately, player 2's y0 position falls on the exact same spot, which means that player 2's card being played on 0,0 fall on the opposite side of the virtual table. This doesn't make a lot of sense.  

In this screenshot, you can see a card played on (0,0) by player 2 (The targeted one) from their perspective. 

[![](http://i.imgur.com/JUmcll.jpg)](http://i.imgur.com/JUmcl.jpg)

I believe player 2's y0 position (and generally y axis) should be modified in such a way that cards played on y0 start with their top border on the separating line.If this is not possible, then the separating line of the table should be moved so that it falls in the middle of card played on the y0 position, so that the cards played at 0,0 fall exactly between the two sides.

**Comment by brine** [comment]
Is this still a thing? I recall there being a change to how cards are positioned on the table, and the two cards should overlap perfectly if they are moved to the same coordinate.

**Comment by brine** [comment]
I think this is closable now, reopen if something wasnt dealt with

**Comment by kellyelton** [comment]
Brine b like 
![image](http://i1058.photobucket.com/albums/t414/Hungryeric/shots-fired-o.gif)

I be like
![image](http://ak-hdl.buzzfed.com/static/2015-03/2/11/imagebuzz/webdr08/anigif_optimized-18229-1425312599-18.gif)

Graves b like
![image](http://media.giphy.com/media/K4JZpuQI7uBLa/giphy.gif)

Brine also ends with a standard
![image](https://media.giphy.com/media/1pZ2OPIr10cM0/giphy.gif)
