### ISSUE TITLE
<set> should add a property "Hidden"

### ISSUE THREAD

**Issue by snowfrost** [octgn/OCTGN#1510]
I think <set> in set.xml should add a property "Hidden",in order to hidden this set in DeckEditor.
Such as Tokens and Makers set.Maybe people don't want to see them when they edit their decks.

**Comment by sIKE23** [comment]
In the deck editor you can filter out sets  already, what would this do that is different?

**Comment by Soul1355** [comment]
yeah, I mean, it's not critical by any means since users can do this themselves, but I feel like it makes sense that some sets could be marked as essentially "not for deck building."
