### ISSUE TITLE
Deck Editor won't launch since update

### ISSUE THREAD

**Issue by lbarry** [octgn/OCTGN#1513]
Updated to version 3.1.22. Now when clicking "Deck Editor" from the tool bar, nothing happens. Completly removed the install and tried again. Same result.

**Comment by Soul1355** [comment]
Do you have only one game installed? That's my first guess as it is something I realize I didn't test. If so, please try installing another game. I'm out of town for the weekend, but I'll look into it more as soon as I can

**Comment by brine** [comment]
which game was it

**Comment by lbarry** [comment]
I had 3 games installed I think. I can run 3.1.21 without issue. In 3.1.22, after I click "Deck Editor" and get no pop-up or anything, then go into Game Manager and attempt to delete a game, it tells me I can't delete a game while editing decks, so something thinks it launched.

**Comment by brine** [comment]
in the Options tab, there's an option to enable advanced options.  Check that, then go into the advanced optons and in there there's "Download Test Releases", check that.
Restart OCTGN and let it download the update, then try to load the deck editor again.  After it fails, go to help --> logs --> current --> share and post the link to the error log.

After its done go back to settings and disable the test release box to restart and go back to the normal OCTGN version

**Comment by Soul1355** [comment]
alright, I think I found the problem, It's up on the test build, so if you could follow brine's instructions to test it out that'd be a big help, because it is a bug in the optimizations that .NET does, so it only ever shows up for some people.

**Comment by Soul1355** [comment]
well, actually now it's live, so let us know if it's still a problem.

**Comment by lbarry** [comment]
Everything is now working as expected.
