### ISSUE TITLE
Players would like to be able to zoom when they do not have a Mouse Wheel

### ISSUE THREAD

**Issue by sIKE23** [octgn/OCTGN#1522]
Keyboard Shortcuts to zoom in and out would be optimal.

**Comment by GeckoTH** [comment]
Yes, that would be awesome. I simply gave up attempting to play OCTGN on my laptop a long time ago since occasionally I'd two-finger zoom in on the game, and it became nigh impossible to get to a proper zoom level again to fix it.

**Comment by Soul1355** [comment]
oh, thanks for making a ticket, I got distracted when somebody pointed that out in chat recently and never got to doing anything about it.

**Comment by brine** [comment]
a "reset zoom level" option in the menus would also be useful

**Comment by Soul1355** [comment]
I was thinking about that, I can probably leverage the code that adjusts the view to show new cards. any thoughts on hotkeys? just like +/- or what?

**Comment by iGemini** [comment]
test and stuff

**Comment by brine** [comment]
yea it could probably just detect the total visible area based on where the cards are on the table.  You'll need to ask kelly about the hotkeys tho cuz a bunch of them are reserved.  Worst case scenario its just a menu option

**Comment by Soul1355** [comment]
oh, I suppose I should make sure the whole board is in view too...

**Comment by kellyelton** [comment]
Well wheel zoom is based on the location of the mouse pointer. Could just
zoom the center of the screen, makes the most sense

**Comment by Soul1355** [comment]
ok, but that doesn't answer either of my questions...

**Comment by kellyelton** [comment]
I wasn't trying to, just throwing in my two cents

**Comment by GeckoTH** [comment]
Yeah... and I'm not sure if you're suggesting modifying the fact that zoom
is based on mouse cursor, but I definitely wouldn't recommend changing
that. :-P

**Comment by kellyelton** [comment]
What I'm saying is if the user does +/- (or whatever combo) for zoom in/out on keyboard, it probably shouldn't have anything to do with the position of the mouse cursor, but instead just zoom to the center of the screen.

**Comment by brine** [comment]
Two-finger zoom on touchpads should be working better now, can someone confirm?

**Comment by brine** [comment]
you can now zoom on the table by using the CTRL+PlusKey and CTRL+MinusKey hotkey combos
