### ISSUE TITLE
o8build verify that deck section destinations exist

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1523]
https://github.com/octgn/OCTGN/blob/master/octgnFX/Octgn/Play/State/GameEngine.cs#L485

In the <deck><section> of the game def XML, the 'group' attribute needs to point to a defined card group that is actually defined.  If the linked code line can't find one, then the user will get a generic "cannot load deck - sequence contains no elements" popup error message when they load a deck.

o8build should scan through all the deck sections listed, and make sure that all the destination groups match to groups that were already defined.

**Comment by brine** [comment]
do these not auto-close anymore?

**Comment by Gravecorp** [comment]
i will close it then :P
