### ISSUE TITLE
Timer problem

### ISSUE THREAD

**Issue by sulpures** [octgn/OCTGN#1545]
I need a timer to set up a period in order to make users wait, during which users may pause or cancel the timer to do extra actions. If the time is up, the game will proceed to the next phase. time.sleep() doesn't satisfy this function, anyone lend me a hand? Thanks a lot!

**Comment by kellyelton** [comment]
There's not really a way to do this.

**Comment by sulpures** [comment]
Thanks, kelly. Pity....

**Comment by sIKE23** [comment]
```python

def onGameStart():
	setGlobalVariable("timerIsRunning",str(False))

#This function lets the player set a timer
def setTimer(group,x,y):
		timerIsRunning = eval(getGlobalVariable("timerIsRunning"))
		if timerIsRunning:
				whisper("You cannot start a new timer until the current one finishes!")
				return
		setGlobalVariable("timerIsRunning",str(True))
		timerDefault = getSetting('timerDefault',300)
		choices = ["30 seconds","60 seconds","180 seconds","{} seconds".format(str(timerDefault)),"Other"]
		colors = ["#006600" for c in choices][:-1] + ['#003366']
		choice = askChoice("Set timer for how long?",choices,colors)
		if choice == 0: return
		seconds = {1:30,2:60,3:180,4:timerDefault}.get(choice,0)
		if choice == 5:
				seconds = askInteger("Set timer for how many seconds?",timerDefault)
				setSetting('timerDefault',seconds)
		notify("{} sets a timer for {} minutes, {} seconds.".format(me,seconds/60,seconds%60))
		playSoundFX('Notification')
		time.sleep(0.2)
		playSoundFX('Notification')
		notifications = range(11) + [30] + [x*60 for x in range(seconds/60+1)][1:]
		endTime = time.time() + seconds
		notifications = [endTime - t for t in notifications if t < seconds]
		updateTimer(endTime,notifications)

#This function checks the timer, and then remotecalls itself if the timer has not finished
def updateTimer(endTime,notifications):
		mute()
		currentTime = time.time()
		if currentTime>notifications[-1]:
				timeLeft = int(endTime - notifications[-1])
				playSoundFX('Notification')
				if timeLeft > 60: notify("{} minutes left!".format(timeLeft/60))
				else: notify("{} seconds left!".format(timeLeft))
				notifications.remove(notifications[-1])
		if notifications: remoteCall(me,"updateTimer",[endTime,notifications])
		else:
				playSoundFX('Alarm')
				notify("Time's up!")
				setGlobalVariable("timerIsRunning",str(False))

**Comment by sulpures** [comment]
Cool!

**Comment by sIKE23** [comment]
You will have to get your own sounds or pull those lines out.

**Comment by sulpures** [comment]
Gotcha, thanks dude

**Comment by kellyelton** [comment]
Oh. I was thinking remoteCall but was thinking "That wouldn't work if only one player was in the game"...didn't cross my mind. nice thinking

**Comment by sIKE23** [comment]
That is @ACG8 all the way. I asked for a timer and that is what he came up with, it is quite slick. I use it places where I don't want to hang things up with python type sleeps blocking.

**Comment by sIKE23** [comment]
You can only have one going at a time though. I cant remember the reason why though.

**Comment by fatelesscn** [comment]
@sIKE23 good job thx

**Comment by brine** [comment]
also, if you import the time module, you can run time.clock(), which returns a timestamp you can store into a variable.  So later on in a function you can run ``elapsedTime = time.clock() - storedTime`` (storedTime being the initial timestamp variable) as a stopwatch function.

**Comment by ACG8** [comment]
You can technically have multiples running at the same time, but it severely impacts performance to have more than one.

It can also be used for things other than a timer; for instance, you could use it to create a process that hangs around in the background and passively monitors the state of the game, reacting if certain conditions are true.

**Comment by sIKE23** [comment]
We did that here....

https://github.com/sIKE23/Mage-Wars/blob/master/GameDatabase/9acef3d0-efa8-4d3f-a10c-54812baecdda/scripts/actions.py#L315

**Comment by sulpures** [comment]
awesome！
