### ISSUE TITLE
3.1.238 dlg disp error

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1547]
in 3.1.238
all the dlg window is too big that i cant find the close button or select button

btw in the maximize winodow of octgn is more serious

**Comment by fatelesscn** [comment]
if the cardsize is not the defalut size, in the dlg window to select it the highlight is always for the default..
The right way is in the dlg window use the cardsize to create the highlight

**Comment by brine** [comment]
which dlg window?

**Comment by fatelesscn** [comment]
![q1] (http://upload.ouliu.net/i/20160113123901jbuz8.jpeg)
![q2] (http://upload.ouliu.net/i/20160113124231kkftg.jpeg)
