### ISSUE TITLE
can octgn use data from call a file

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1564]
or read data from net xml file?

**Comment by kellyelton** [comment]
Not sure what you're asking. Are you asking if in python you can read files?

**Comment by fatelesscn** [comment]
yes it is

**Comment by Gravecorp** [comment]
I am unsure if it can read local files but the webread api call can query things on the internet. after that its up to you on how you work with that data.

**Comment by sIKE23** [comment]
Mage Wars reads in txt files. ...

**Comment by Gravecorp** [comment]
then help the dude out with some code snippets :P its not like i am all knowing :P

**Comment by sIKE23** [comment]
I am on the road atm...but the module is up on github....

**Comment by brine** [comment]
please use this issue tracker to submit bugs or feature requests, not to ask for help with game creation
