### ISSUE TITLE
Python File write error

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1572]
i import os ,sys

and use open() to open a file

it can use file.read correctly

but if i use file.write(str)

it be error:

IOError: System.IO.IOException: Can not write to C:\Users\Administrator\Documents\Octgn\GameDatabase\c79b3612-748e-430b-a578-033936365582\scripts\123.txt
   in IronPython.Runtime.PythonFile.GetWriter()
   in IronPython.Runtime.PythonFile.WriteNoLock(String s)
   in IronPython.Runtime.PythonFile.write(String s)
   in Microsoft.Scripting.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   in System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   in Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   in IronPython.Compiler.PythonCallTargets.OriginalCallTarget1(PythonFunction function, Object arg0)
   in IronPython.Runtime.FunctionCaller`1.Call1(CallSite site, CodeContext context, Object func, T0 arg0)
   in System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   in Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   in Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   in IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   in IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   in Octgn.Scripting.Engine.Execute(Object state) at c:\projects\octgn\octgnFX\Octgn\Scripting\Engine.cs:line 530

**Comment by sIKE23** [comment]
I think that this is not the right place to ask a question like this, as
you are importing you own py modules at this point and I don't think the
OCTGN devs can really help. However if you were to hop into the #OCTGN IRC
channel there are people there that might be able to assist.

//FC

**Comment by kellyelton** [comment]
#572 
What exactly are you trying to do? If you're just trying to save settings, we already have an api for that.

**Comment by kellyelton** [comment]
Also, here is a [link to the chat](http://webchat.freenode.net/?channels=%23octgn&uio=MTY9dHJ1ZSYyPXRydWUmOT10cnVlJjExPTM2OQ5f)

You can also chat with us via our [google group](https://groups.google.com/forum/#!forum/octgn-dev)

**Comment by kellyelton** [comment]
Since there has been no update on this in over 6 months I'm closing this. Feel free to comment, we'll open it back up if it's necessary.
