### ISSUE TITLE
table.board game splashscreen

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1582]
i just want to show a pic to the player for a few seconds,tha with out the cards in table.
- kelly -
  Make it so that games can have an intro image that displays for a few seconds when the game starts.

**Comment by kellyelton** [comment]
I feel like this ticket is confusing. I'm not really sure what you're asking for.

**Comment by fatelesscn** [comment]
i wan to show a board in front of the table.the cards in table is under it.

**Comment by kellyelton** [comment]
What is this board? Just a picture? Do the users drag it around or interact with it at all?

**Comment by fatelesscn** [comment]
just a pic,there is no interact with it ,i just want to show it for a few seconds,like a interlude

**Comment by kellyelton** [comment]
Ohhhh, kind of like a splash screen for your game?

**Comment by fatelesscn** [comment]
yes ,how can i do it , and sorry for my english.

**Comment by kellyelton** [comment]
There's currently no way. I will update this ticket to make what you're asking for more clear and we'll set it as a feature request.

**Comment by kellyelton** [comment]
Ok...give me more details....is this just for the start of the game? What is the purpose of the image? Will it show up periodically throughout game play? Give me more details on your plans.

**Comment by fatelesscn** [comment]
for i.e

when a phase start ,i want to show it like this
![q1] (http://upload.ouliu.net/i/20160519115730bd2wn.jpeg)

or for a card ablility like this

![q2] (http://upload.ouliu.net/i/201605191202367q30d.jpeg)

it not must be a board,but in this time ,i only can use board to create it.

**Comment by torrentails** [comment]
A workaround you could use for the time being, is to create a card set with `hidden="True"` and make each of the image you want into a custom sized card in that set. Then whenever you need to display an image at the beginning of a phase or whatever, just create the appropriate card, `sleep()` for a second or two, then `delete()` the card.

**Comment by kellyelton** [comment]
That's not a half bad solution. Could also add a default action that
deletes the card, If you wanted to wait for user input. Could even make
cards that look like buttons lol.

**Comment by fatelesscn** [comment]
I tried this way before,but there is a problem:See this card card is the opposite of the opponent,I have to rotate it to the opponent.

**Comment by kellyelton** [comment]
I feel like a valid solution has been provided to solve your issue. If you don't think so we can continue discussions. Otherwise I'm going to go ahead and close this.
