### ISSUE TITLE
Double-sided card back images are not being displayed after recent update.

### ISSUE THREAD

**Issue by cribolouf** [octgn/OCTGN#1584]
After a recent update, every card in the pathfinder module that is dual-sided (characters, roles, locations, adventures, scenarios, and adventure paths) are now only displaying properly for the front side. The reverse side of all dual-sided cards is showing up as a proxy. I have discussed this issue with Gemini in the chat, and he informed me to open up a ticket about it.

**Comment by brine** [comment]
fix coming soon, don't worry about having to redo your image packs
