### ISSUE TITLE
Disable custom actions in contextual menu

### ISSUE THREAD

**Issue by raohmaru** [octgn/OCTGN#1609]
Like the new 'getName' parameter for action tags in the game definition, it will be useful to have a parameter to decide whether to show or not an action in the contextual menu. With this, developers will be able to show only the custom actions related to specific types of cards (or groups).

**Comment by brine** [comment]
the 'showIf' parameter should be what you want

**Comment by raohmaru** [comment]
Didn't know about that parameter, I should have searched better at the wiki.
It solved my issue. Thanks!
