### ISSUE TITLE
Can't add a custom feed

### ISSUE THREAD

**Issue by veyDer** [octgn/OCTGN#1617]
Whenever I add a custom feed in the Games Manager it is removed after the restart of OCTGN.
I've also tried to put anything (figured out it could be just the URL of the feed) in the feeds.txt file but it didn't make any difference. Moreover, after I've added the feed manually, the contents of the feeds.txt file were removed.

The feed I'm trying to add:
https://www.myget.org/F/historia-cards/

**Comment by veyDer** [comment]
Tried also with some other feeds that someone else posted, like:
https://www.myget.org/F/geminioctgn

and the game installs fine, yet after the restart it's the same thing: no game feed in the Games Manager. Now I can't even uninstall that game, apart from manually deleting the directories from GameDatabase and ImageDatabase

**Comment by brine** [comment]
Are you running on a VM, or set the datadirectory to a location outside of your windows install drive?

**Comment by veyDer** [comment]
No, but can it be the issue that I get a warning about running OCTGN as the administrator every time it starts?

OCTGN is installed in [User]\My Documents\OCTGN (running on Windows 7)

**Comment by veyDer** [comment]
Answering myself: no difference whether I run it as a regular user or administrator.

**Comment by veyDer** [comment]
Reinstalling OCTGN didn't help either.

**Comment by brine** [comment]
okay, got some troubleshooting steps.  Can you attempt to add a feed, then close down OCTGN, reload it, verify that the feed is not there, then go help->logs->current->share, and send the links to both the current and previous logs?

**Comment by veyDer** [comment]
When trying to do "Help > Logs > Current > Share", I'm getting an error "There was an error uploading the text".

I was able to save the files using "Help > Logs > ... > Save As":

[prevlog.txt](https://github.com/octgn/OCTGN/files/680148/prevlog.txt)
[currentlog.txt](https://github.com/octgn/OCTGN/files/680149/currentlog.txt)

**Comment by brine** [comment]
alright i just had it happen on my end so we can confirm replicate this issue

**Comment by kellyelton** [comment]
Fixed by 160c3a402650f4c013f24ea711d321d5a83b62c5
