### ISSUE TITLE
Unable to answer a private message

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1620]
Sometimes, after receiving a private message from someone we have not yet started a conversation with since last OCTGN start-up, the chat window gets loaded constantly (contrary to a typical situation where it takes less than a second to load), which therefore makes you unable to answer this message. Re-opening the chat window doesn't help. As far as I know the only way to solve it is to restart OCTGN.
I don't know if such issues happen to other users as well. If it's anyhow relevant my os is Windows 7 32bit.

![chat windows loading](https://cloud.githubusercontent.com/assets/24973388/21741038/2b8751fa-d4cb-11e6-8190-d4b4fac85cfa.png)

**Comment by Wirox** [comment]
It sometimes even happens when you're the one to start a conversation.

**Comment by Wirox** [comment]
Closing the chat with 'Chat -> Leave Chat' seems to fix the issue.

**Comment by BenMatteson** [comment]
probably looking at starting from scratch if this ever comes back
