### ISSUE TITLE
Games don't update from custom feeds

### ISSUE THREAD

**Issue by veyDer** [octgn/OCTGN#1625]
When I push a new package to MyGet repository, OCTGN doesn't update the game upon load.

Attaching the log.txt file, lines 104-108 are the related error.

[log.txt](https://github.com/octgn/OCTGN/files/698361/log.txt)

**Comment by brine** [comment]
update your OCTGN client, version 382 fixes this.

**Comment by veyDer** [comment]
Thank you very much!
