### ISSUE TITLE
Cannot get the card.model of a facedown card

### ISSUE THREAD

**Issue by veyDer** [octgn/OCTGN#1626]
Issue #1426 was closed but I'm still getting this behaviour (getting None instead of the GUID).

**Comment by kellyelton** [comment]
What scriptApi version are you using?

**Comment by brine** [comment]
yea for some reason the fix was done in 3.1.0.1 but not in 3.1.0.2... dunno if it was intentional or not

**Comment by kellyelton** [comment]
No I don't think so. Other sections that were commented out related to `IsFaceDown` were left commented. It looks to me like a mistake.

**Comment by kellyelton** [comment]
If you're using ScriptAPI v 3.1.0.2, then migrate on over to this other ticket, #1627 and we'll close this one.

Otherwise, let us know.

**Comment by veyDer** [comment]
I'm using v 3.1.0.2

**Comment by kellyelton** [comment]
Ok, so this is happening in 3.1.0.2?

**Comment by veyDer** [comment]
Yes, it's in 3.1.0.2

**Comment by brine** [comment]
see #1627
