### ISSUE TITLE
Logging-in with e-mail and multiple accounts

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1632]
If you have more than one account created with certain e-mail, you can use your e-mail to log in only to your most recent account.

**Comment by kellyelton** [comment]
There are no accounts like this. Any account that was not the most recent had its email removed and requires a new email to use it. 

I don't think we plan on allowing multiple usernames per email, it just makes things more complicated, and we'd be the only software doing it.

That's just my 2 cents though.

**Comment by Wirox** [comment]
Oh, ok, it explains a lot.
