### ISSUE TITLE
'Sorted' option in the Deck Builder displays wrong card when double-clicked

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1645]
When a pile is set to 'Sorted' in the Deck Builder and you double-click a card in this pile, it incorrectly shows a card of the same index, but from 'Manual' order.

Example:
'Manual' order of a pile is [C, A, B]
'Sorted' order of a pile is [A, B, C]
While in 'Sorted' order,
double-clicking A displays C,
double-clicking B displays A,
double-clicking C displays B.

**Comment by brine** [comment]
leaving some notes for whoever can figure this out:

I set a breakpoint here: https://github.com/octgn/OCTGN/blob/master/octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs#L543
so I could watch what card is being selected at each click.  From what I can tell, it returns the card from the original unsorted collection, regardless of how many times its clicked.  

So something's forcing the first click to show the correct image, but it certainly isn't this part of the code

**Comment by kellyelton** [comment]
Reference probably messed up I'm sure. Is this a new issue?

**Comment by Wirox** [comment]
I haven't noticed it earlier but I also wasn't really using 'Sorted' option before, so I'm not sure.

**Comment by brine** [comment]
did someone look into this yet?
