### ISSUE TITLE
How to search in card database

### ISSUE THREAD

**Issue by fab64443** [octgn/OCTGN#1648]
Hi,

Is it possible to search in the card database to find cards matching some properties like askCard function but without user input/validation ?

Sincerely.

**Comment by brine** [comment]
I don't believe its exposed to the API but it should be easy to implement, considering askCard already has the tech involved.

So you're looking for basic card database queries, and return a list of matching card GUIDs?

**Comment by fab64443** [comment]
Hi,
Yes, basic queries is enough. It will be more flexible than GUIDs hardcoding. 
Thanks

**Comment by brine** [comment]
https://github.com/octgn/OCTGN/pull/1653/commits/4b8422193508f69281c56d450d2be6d57d42c15b

**Comment by brine** [comment]
this should be closed as fixed, see queryCard API
