### ISSUE TITLE
Request: Add chat logs

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1668]
It could be quite helpful if chats (mainly private messages, but this could be done for lobby and in-game chats, too) were logged somewhere, so users could have access to any of the past messages.
Two main arguments for chats being logged are:
1. Sometimes you can close OCTGN not knowing there are some messages you haven't read yet or shortly after receiving one, which used to make you lose it irreversibly.
2. For various reasons users may just want to re-read any of their older messages.

**Comment by BenMatteson** [comment]
in game chat is now saved as part of history, and out of game chat has been removed
