### ISSUE TITLE
Immediate disconnection after starting a game

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1674]
Sometimes all players get immediately disconnected after starting a game. Reconnecting to such a game is not possible.

**Comment by brine** [comment]
on first guess this would suggest that the server's game state is crashing and disconnecting the players.  It wouldn't be able to recover connection for the players

**Comment by brine** [comment]
I have to imagine that this bug was in the older server code and doesn't port over to the current implementations.  Open a new ticket if it's still occurring.
