### ISSUE TITLE
Alternate value inconsistent between players after dragging from table to group

### ISSUE THREAD

**Issue by blakewedwards** [octgn/OCTGN#1677]
Encountered this with the Legend of the Five Rings LCG version from Community Games.

![alternate_issue](https://user-images.githubusercontent.com/5283603/31313115-5cc6aa9c-ab8d-11e7-9349-7e2f329d0368.png)
- Run two instances of OCTGN and join the same game. Load decks and run setup for each player (alt-click the table and Setup).
- As the game creator, double click the Water Ring to switch it to Political (sets an alternate)
- Click and drag the Water Ring to your Claimed Rings group (rightmost group beside your decks)
- Expand the group and observe that the ring is showing as Military (no alternate)
- As the other player, switch to the opponent's group view and expand their Claimed Rings group
- Observe the same ring showing as Political (alternate set)

In case this is the plugin's error, here's its OverrideCardsMoved event handler:
```
<event name="OverrideCardsMoved" action="move_cards"/>

def move_cards(args):
  for i, card in enumerate(args.cards):
    from_group = card.group
    alternate = card.alternate # Preserve the alternate state for rings

    if args.toGroups[i] == table: # Dynasty cards should move to table facedown, unlike conflict which move as faceup
      card.moveToTable(args.xs[i], args.ys[i], True if from_group == me.piles[DYNASTY] else not args.faceups[i])
      if card.type == TYPE_ATTACHMENT and from_group != table:
        card.sendToBack()
      else:
        card.index = args.indexs[i]
    else:
      card.moveTo(args.toGroups[i], args.indexs[i])

    if card.type == TYPE_RING:
      card.alternate = alternate
```

**Comment by brine** [comment]
is this still happening?

**Comment by brine** [comment]
I’m going to try and tackle this issue this week.  I did some breakpoint tests and it seems like the server is bouncing back an extra switchTo() message to the controller of the card, reverting it back to its default alt.

There’s definitely a bug here.  In the meantime though, you might be able to bypass it by cutting out the alternate setting code from the override event and putting it in a normal moveCards event.  It gets sequnced a little differently so maybe that’ll fix it?

You’ll prob need to set an event for both moveCard and scriptedMoveCard
