### ISSUE TITLE
SetPlayerColor crashes for player IDs above 38(ish)

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1691]
https://github.com/octgn/OCTGN/blob/c51f51dc9accc337d34f50653c7a526902358d43/octgnFX/Octgn/Play/Player.cs#L370-L373

This line subtracts 18 from the player ID value, presumably to loop through the color list again when it runs out of colors.  If there's more than 38 players though, the ID will still fall out of the range.

Either stick the Idx-18 into a while loop, or do some modulo/division math to make sure the ID value stays within 1-18.

**Comment by Wirox** [comment]
> to make sure the ID value stays within 1-18.

Within 1–18 or 0–18? If you want players with `idx` above 18 to loop through the gray color as well, it should be 0–18.

If it's 1–18, it should be `idx = ((idx-1) % 18 + 1) % 18;`
(the other modulo because for `idx = 0`, `(idx-1) % 18 + 1 = 18`
If it's 0–18, it should be `idx = idx % 19;`

**Comment by Soul1355** [comment]
ok, after too much digging, player IDs start at 1. also, there are actually 20 total color values apparently, so it should go 1-19. what you have up top is close, but I'm pretty sure it returns `-1` for `idx = 0` so the `min()` doesn't help. I'm pretty sure it'll never actually get a 0, so it's not really an issue, but to be on the safe side, I'd say it should just be
```c#
if(idx == 0 || idx == 255)
     idx = 0;
else 
     idx = ((idx-1) % 18) + 1);
```
also, just realized, not sure why that array is getting instantiated every time, should probably just be a static...

**Comment by brine** [comment]
I also think we should remove the black color from the array and specify that to the local player

**Comment by Soul1355** [comment]
actually... that is probably the only place we actually need to deal with that, and could just strip out several cases and simplify that operation to do that... I'll give it a try

**Comment by Wirox** [comment]
>but I'm pretty sure it returns `-1` for `idx = 0` so the `min()` doesn't help

Depending on how you define modulo for negative numbers, `(-1) % 18` is either -1 or 17, so if you add 1 to that it's either 0 or 18 (notice the formula is `(idx-1) % 18) + 1`). So `min()` does help, but I guess if that `idx == 255` is needed (not sure what its purpose is), you can't avoid if's either way.
And yeah, I've just checked and there are indeed 20 colors in the array, so just use modulo 19 instead.

**Comment by Soul1355** [comment]
Of right, my bad, I got as far as figuring out how it handles the negative and forgot to do the +1. So I just meant that you don't need it for c#. I then screwed up my environment trying figure out about the 255... So if somebody else wants to deal with it, I might be a while.
