### ISSUE TITLE
client freeze when tab + hovering on card

### ISSUE THREAD

**Issue by d3ath3ater** [octgn/OCTGN#1693]
the game freeze, when coincidently pressing tab while mouse is hovering on card and right click.
end task octgn will show prompt of exit game but cannot press anything.

game freeze 3/10 times when hovering on card.

OS: Windows 10
Plugin: FFTCG

**Comment by brine** [comment]
Does this happen on any card, or are there specific ones that it always freezes on?

**Comment by d3ath3ater** [comment]
random cards.

**Comment by d3ath3ater** [comment]
i have collected the dump when it freeze. how do i upload?

**Comment by brine** [comment]
Our log sharing service is down right now, but you can usually share them through gist (githubs code sharing service) or pastebin

**Comment by d3ath3ater** [comment]
it is a memory dump and is 1gb size. .DMP file.

**Comment by brine** [comment]
oh I thought you were talking about the OCTGN error logs, those are in documents/octgn/OCTGN/logs

**Comment by d3ath3ater** [comment]
ok, once it happen again, i will keep the logs and upload here.

**Comment by d3ath3ater** [comment]
2 occurance happen.

1. game freeze when hovering on card (card animation in progress), right click. end task, brings to reconnect screen, chat is reconnected but cannot chat but stuck at reconnect screens stays there and nothing can be click. hotkey still usable to move phases.
https://pastebin.com/HsgpXyt7

2. client freeze when tab and right click happen at the same time. end task, FFTCG plugin, brings me back but stays at reconnect screen. hotkey still usable but nothing can be click other than cancel to disconnect game.
https://pastebin.com/Nabep8q2

**Comment by d3ath3ater** [comment]
i have just re-install the octgn. will monitor again.

**Comment by d3ath3ater** [comment]
happens today after re-installation.

game freeze when tab (change phase) while hover on cards.
https://pastebin.com/bnxbLXSL

**Comment by brine** [comment]
I don't think we were ever able to replicate this issue, please let us know if it still happens
