### ISSUE TITLE
Malwarebytes Popping up for Blocked Domain: q.dreniq.com

### ISSUE THREAD

**Issue by konals** [octgn/OCTGN#1694]
When I click refresh on the game list or download Arkham Horror LCG, Malwarebytes pops up a blocked domain alert, saying the domain is malicious. A few google searches have indicated to me that this is caused by a parked domain? Are there any expired domains that are still being referenced in the game list/downloads?

![malwarebytes](https://user-images.githubusercontent.com/2679610/34329155-324a7090-e8ba-11e7-8c77-4102763d413c.png)

**Comment by brine** [comment]
does this happen for other games as well?

**Comment by konals** [comment]
I just tried Netrunner, same thing. It popped up/occurred near the end of the download/install time.

**Comment by konals** [comment]
Uninstalling Netrunner also gave me the pop-up.

**Comment by brine** [comment]
have you done a full virus and malware scan on your PC recently?

**Comment by konals** [comment]
Yes, I have. Nothing wrong. Other software/sites are not giving me this issue.

**Comment by konals** [comment]
Okay, if I filter the list of games via the categories at the top:

![image](https://user-images.githubusercontent.com/2679610/34329429-59d1197e-e8c5-11e7-8898-7bf54ae22189.png)

The only case where it shows that error popup is when I select "All" or "The Spoils". The Spoils doesn't have an image, so my assumption is that it's a broken link and my system doesn't like whatever redirect is 'parking' it.

**Comment by brine** [comment]
yeah possibly, my malwarebytes isn't detecting anything for those games.  From what I've read, there were some viruses that created redirects to that domain, but other than that there shouldn't be anything in OCTGN's installers that go outside of myget.org

**Comment by konals** [comment]
Okay, I found the problematic page, it is indeed the icon for Spoils.

I did the search to find the myget url.

![image](https://user-images.githubusercontent.com/2679610/34329486-39a648b0-e8c8-11e7-94fb-ec181ee45603.png)

![image](https://user-images.githubusercontent.com/2679610/34329487-4b7db5aa-e8c8-11e7-99ef-52b5c2da94ff.png)

![image](https://user-images.githubusercontent.com/2679610/34329490-51633e7c-e8c8-11e7-967b-c7c461fef4cb.png)

![image](https://user-images.githubusercontent.com/2679610/34329491-5e5e376c-e8c8-11e7-8cf5-a1d547a7fbd3.png)

![image](https://user-images.githubusercontent.com/2679610/34329493-665611a6-e8c8-11e7-9c31-51d7646dad9f.png)

Going to the URL for the icon:

![image](https://user-images.githubusercontent.com/2679610/34329495-78ba3da4-e8c8-11e7-862f-43fcae078662.png)

So yeah, that's what is causing the issue. I think MalwareBytes is just blocking whatever is parking that URL. The URL doesn't seem to load for me.

**Comment by konals** [comment]
![image](https://user-images.githubusercontent.com/2679610/34329522-514dae6c-e8c9-11e7-9b5f-1213106e9ffd.png)

**Comment by brine** [comment]
ok we'll have to take a look at changing this.

**Comment by Soul1355** [comment]
just wanted to pop in and say thanks for working through that, love it when people help out where they can

**Comment by konals** [comment]
No problem, I wanted to figure out what it was before I threw the download over to my friend, and after a bit it just became a puzzle I wanted to solve :D

**Comment by brine** [comment]
it looks like this has been resolved
