### ISSUE TITLE
Crashing when creating an offline game

### ISSUE THREAD

**Issue by Kwaice** [octgn/OCTGN#1718]
Hello,

Since the latest OCTGN update, OCTGN keeps crashing when i'm trying to start a game.

This is the screen i'm getting,

![octgn crash](https://user-images.githubusercontent.com/25953788/35437291-005bf36e-0292-11e8-9b61-71091b039e3c.png)

**Comment by brine** [comment]
thanks for the report.  There are a few areas that still need to be fixed after the downtime, offline games included.  Online game hosting should be working in the meantime.

**Comment by brine** [comment]
fixed
