### ISSUE TITLE
Problems with synchronization between players

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1724]
Since the latest downtime there seem to be some issues with synchronization between players. Even if no disconnections occur in the game, it's possible a player does some action and changes caused by it aren't seen by everyone.

**Comment by brine** [comment]
how frequently, and how quickly from the start of the game, would you guess that this is happening?  I'm having a really hard time trying to replicate it on my end

**Comment by Wirox** [comment]
I'm not too sure since, as a player, I only see my own board, so there could've been situation where other players saw some cards that weren't supposed to be on the table, but didn't report it. But if I were to consider only those cases which I've personally observed, I would say it happens more or less once per hour (keep in mind most of my games since the latest downtime were multiplayer, which most likely affects frequency – although I've seen cases of this issue in 1v1 games as well). I don't know if it's anyhow related to how long the game has been on, but as far as I remember I haven't experienced this throughout the first 15 minutes of any game.

**Comment by brine** [comment]
please let us know if this is still occurring with the latest updates

**Comment by Wirox** [comment]
Not quite this exact problem, but sometimes a log message isn't displayed in for everyone (like one about a player changing one of their player counters). I've noticed it two times so far, but it's very likely it has been happening more often as there are many messages I simply don't pay attention to.

**Comment by Wirox** [comment]
The issue with log messages happened again, so I believe the ticket should be re-opened.

**Comment by brine** [comment]
apparently we don't actually have a ticket open for the reconnection bugs either
