### ISSUE TITLE
Disappearing cards and losing control over them.

### ISSUE THREAD

**Issue by swider33** [octgn/OCTGN#1728]
Since one of the recent updates all Doomtown Reloaded players complain about the same bug. When we reveal our draw hand, group of 5 cards per player, they are not displayed properly, some of them are invisible for both players, only dragging and dropping them solves the problem. Additionally, the same cards aren't discarded properly, some of them stay on the table, in this situation controller of the cards doesn't see them, but the opponent does. To solve this opponent has to take control over the cards and discard them manually. This error occurs almost every time a player reveals his hand.
The other similar issue is with starting characters, randomly (immediately after loading deck) at least one of them can be invisible and becomes visible only if moved around or attachment is played on them.

**Comment by swider33** [comment]
Thanks a lot.

**Comment by brine** [comment]
please let us know if this is still occurring with the latest updates
