### ISSUE TITLE
non-host players can change spectator status of anyone

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1745]
A player joining a game can change the spectator setting of any other players in the game lobby.  This is a bug introduced during the big downtime.

I don't remember exactly how this worked previously.  I believe the host player was allowed to change the spectator status for everyone, but the other players could only toggle for themselves.

**Comment by Wirox** [comment]
It think it did exist before. I remember that newcomers would always repeatedly click 'Play' buttons, thinking it would start the game. I'm just not 100% sure if they were able to change other players' spectator status.

**Comment by brine** [comment]
yeah based on what I've dug up its always been this way.
