### ISSUE TITLE
"Load A Preset Deck" game option

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1760]
A menu option which opens up the "load a deck" file browser defaulting to octgn/GameDatabase/{GAME ID}/Decks, instead of octgn/Decks.  If the installed game doesn't have one, hide this menu option.

By extension this feature should remove the code that copies the game's preset decks into octgn/Decks/{GAME NAME}, as that functionality wouldn't be needed.

This would be beneficial because the current code just dumps the game's preset decks into the decks folder, but doesn't have any version control.  If, for example, I renamed one of the decks in the game def, that deck will be copied over and functionally duplicated.  Under this new feature, the Preset Decks available to the game will always be synced to the current game definition version (as the game's database installation always gets wiped clean after each update).

**Comment by kellyelton** [comment]
We should change the default location when opening that dialog.

**Comment by brine** [comment]
merged.
