### ISSUE TITLE
I cannot download

### ISSUE THREAD

**Issue by dannydice64** [octgn/OCTGN#1762]
I tried to download OCTGN 3.2.75.0, but my Anti Virus blocked it (I'm using Microsoft Security Essentials), because it has a Trojan Malware. I hope you can resolve this issue :(

**Comment by brine** [comment]
run windows updater and make sure you've got the most recent virus definitions

**Comment by dannydice64** [comment]
Before we close this, I'm using Windows 7 and what update should I download? (I don't rely on Windows Updater, I prefer manual update)

**Comment by brine** [comment]
anything involving security essentials

**Comment by dannydice64** [comment]
Before I close this thread here's my question, can I use my old installer?

**Comment by brine** [comment]
MSE is tied with a lot of windows services, if you pick and choose what gets updated through windows updater, then there's no guarantee anything will work properly.

The steps we've used in the past to fix this issue for other users was:

1) run windows updater to make sure all windows services are up to date
2) check for windows security essentials (or windows defender) updates both through updater and through the respective programs update checkers
3) check the antivirus software for any pre-existing flagged OCTGN installers, and if an option to de-flag or whitelist them is possible, do so
4) restart computer
5) download a fresh installer from octgn.net and run that

**Comment by dannydice64** [comment]
Man! Even I installed the latest Windows Update + MSE still detects and blocks the latest installer :(
