### ISSUE TITLE
various issues occurring after a game reconnect

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1767]
here's a compilation of errors that continue to occur since the big server code update a couple months ago:

- players being unable to reconnect (waiting for players screen doesn't go away)
- game states being messed up after a reconnect
- game actions being unresponsive after a reconnect
- server attempting to reconnect players to a different game in progress

**Comment by magedsabri** [comment]
Same issue, it is actually making playing online with friends impossible

**Comment by kellyelton** [comment]
I think most of these have been resolved. If not, we'll create new issues as they arise.
