### ISSUE TITLE
Feature request: Allow moving cards between sections in the Deck Builder via a keyboard hotkey

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1780]
Right now the only way to move cards between sections is to drag them, which becomes quite tiresome when your decklist is more than one-screen-long, especially when you want to move a lot of different cards.

A keyboard hotkey to move a card to the nth section (preferably without changing focus between sections, but that's up for discussion) would make this process much faster and more convenient.

**Comment by kellyelton** [comment]
Can you provide more information on your request please? I'm not sure I quite follow what you're asking.

**Comment by Soul1355** [comment]
we talked about this one, basically some way to move cards between deck sections via hotkey, so in the case of, say, a 100 card singleton, you don't have to scroll past all 100 cards to move the top card to a lower section. 

didn't get anything concrete, but the ideas thrown around were some_sensible_modifier(s)+up/down to move all of a card to the previous/next section, and follow them, focusing them in the new location (to allow moving cards to more than just adjacent sections). 
or, modifier(s)+1-0 to move single cards to arbitrary sections (this limits the functionality to 10 sections, but feels like a better option)

its one of those things I'm not really sure how best to do it yet, but seems like a good thing to have.
