### ISSUE TITLE
What font is it？

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1782]
![image](https://user-images.githubusercontent.com/16491120/42198310-ce4d6cdc-7eb9-11e8-94d8-eee9a9d12e5c.png)
May be miss font file.

**Comment by brine** [comment]
I can't tell based on this if the font you're using in the game is broken (which would be an issue with the game package), or if OCTGN is having troubles rendering it.  I'm leaning on the first option, but would need more background info here

**Comment by fatelesscn** [comment]
Octgn V3.2.75 is ok but in V3.2.83 is wrong.
I think there is a change of fonts on this window.
Btw:  The problem is the Chinese character.

**Comment by brine** [comment]
run it through o8build

**Comment by fatelesscn** [comment]
![image](https://user-images.githubusercontent.com/16491120/42303450-f22433e8-8053-11e8-8107-41e29c0f33c5.png)
o8build is ok but still displays errors.

**Comment by kellyelton** [comment]
Can you provide us a way to test/debug this?

**Comment by BenMatteson** [comment]
closing as we have no way to test or determine if this is still a problem.
