### ISSUE TITLE
Wiating for Other Users Window blocks play even after reconnect

### ISSUE THREAD

**Issue by brusser** [octgn/OCTGN#1785]
Happened 2 times now. A user gets disconnected but then reconnect however the Waiting for Other Users window stays up for all other users. The reconnected user is able to continue playing and it updates on the other users game boards. Read this post had the same issue in 2014. Seems keyboard commands still work.
http://www.cardgamedb.com/forums/index.php?/topic/15867-octgn-waiting-for-other-users/

[log.txt](https://github.com/octgn/OCTGN/files/2194050/log.txt)

Looking for a workaround? Is there a way to rejoin a game or save a game and restart it?

**Comment by brine** [comment]
this is part of the massive reconnect bugs that have been occurring, once that gets fixed we should see all these issues go away

**Comment by brine** [comment]
I believe its just coincidental that its the same symptoms as from 2014, though. There was a long stretch of time that it did work between then.

**Comment by kellyelton** [comment]
Fixed by 802bb5e418c2b319aa74c9527c5129aca9d50a0b
