### ISSUE TITLE
Feature request: Add a way to shuffle any group, not just piles

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#1802]
Currently only [piles](https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.2-API-Reference#pile-class) can be shuffled, but I don't see a reason not to expand it for any [group](https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.2-API-Reference#group-class).

**Comment by brine** [comment]
I assume this was in reference to shuffling the hand group.  If so, this can be closed because the hand considered a pile now.

If this is referring to shuffling a group of cards (i.e. a selection on the table), please submit as a new ticket.
