### ISSUE TITLE
Odd Behavior With Automatic OCTGN Updates

### ISSUE THREAD

**Issue by zz1000zz** [octgn/OCTGN#1828]
When OCTGN detects there is a new version I need to download, it opens the download page in my browser and downloads the file but also continues on to open my current version of OCTGN.  The result is an outdated version of OCTGN runs even as a new version is downloading.  Additionally, it appears this causes OCTGN to skip some other steps of the normal boot up process.  I believe it skips checking for updates to game packages, and I know for certain it skips the step where it would normally copy images from set folders within the GameDatabase over to the ImageDatabase (and then delete them from the GameDatabase).

The issue is relatively minor as the user can fix it by closing OCTGN and manually running the freshly downloaded installer.

**Comment by brine** [comment]
is this still happening with current installer versions?

**Comment by zz1000zz** [comment]
Nope.  The problem appears to be fixed.

**Comment by kellyelton** [comment]
I'd still like to take a look at this at some point and see if there are any improvements that can be made here.

**Comment by kellyelton** [comment]
Does it automatically run the installer, or does it show a dialog saying "Downloading the latest version failed".

I took a minute to look through the code. If it automatically runs the installer, we can close this.
