### ISSUE TITLE
Unable to run with non-admin Windows accounts

### ISSUE THREAD

**Issue by ventrebd** [octgn/OCTGN#1838]
The new installer causes issues for Windows configurations where the user account is not an administrator.

Sequence of steps:
1. Run OCTGN installer (v3.3.111.0) as regular user
2. During install, install directory is automatically set to C:\Program Files (x86)\OCTGN and data directory to C:\Users\regular_user\Documents\OCTGN
3. Windows prompts to upgrade to admin account (requiring authentication) -- note this is not User Account Control, since regular_user has no admin rights.
4. Install appears to complete.
5. Try to run OCTGN as regular user account.
6. Receive error "OCTGN is not installed.  Please install OCTGN." (from octgnFX/Octgn/App.xaml.cs)

Root cause is that the registry keys for OCTGN are installed in the user hive for the admin account (with Data & Install directories as specified during the installer), but there's no registry key for the regular user (so the default lookup fails).  Additionally, the registry key in the admin's user hive points to the regular user's Documents directory.  The old installer never had this issue (and never required admin rights in the first place, as the exe was installed in the regular user's documents folder).

Also, trying to bypass this by not allowing the installer to elevate (i.e., setting install directory to location writable by regular user and/or cancelling out of password prompt) was unsuccessful.

Some possible fixes:
- Allow for non-admin installation into non-privileged location (i.e., user's documents folder)
- Add install directory registry key to local machine hive instead of current user hive, then allow for per-user data directory, prompting on initial program startup (should enable full multi-user support)

Thanks.

**Comment by BenMatteson** [comment]
Nice. I forgot nobody made an issue for this yet. 

You're probably aware but for now you can work around this by adding the appropriate registry entries manually for the user that's actually supposed to have them. 
[HKEY_CURRENT_USER\Software\OCTGN]
"InstallDirectory"="C:\\Program Files (x86)\\OCTGN\\"
"DataDirectory"="C:\\Users\\<user_folder>\\Documents\\OCTGN\\"

**Comment by ventrebd** [comment]
Thanks; manually adding the keys seems to have done the trick (wasn't sure if that would break anything else).

Leaving issue open in case you want to use it to track the code changes.

**Comment by kellyelton** [comment]
We plan on fixing this by moving the registry entries into HKLM instead of HKCU.

**Comment by ventrebd** [comment]
Not sure if this is what you intended, but please leave the DataDirectory key in HKCU, with InstallDirectory in HKLM.  This lets each user maintain their own configuration, and keeps other user accounts from attempting to open folders to which they won't have access (which would happen with an HKLM DataDirectory).  Maybe replace the original registry check in octgnFX/Octgn/App.xamlcs with something like the following:
- if no HKLM/Software/OCTGN/InstallDirectory, error like existing
- if no HKCU/Software/OCTGN/DataDirectory, prompt user to pick folder & set key
- Use folder from HKCU/Software/OCTGN/DataDirectory as database location

**Comment by kellyelton** [comment]
I know what I said. What's the alternative? OCTGN installs into Program Files. If another user tries to run OCTGN then they won't have any registry keys showing the install directory or data directory if it's set in HKCU.

**Comment by ventrebd** [comment]
Put InstallDirectory key under HKLM so that it is globally accessible; since the value is probably a privileged directory, any auto-updater is going to need admin access to run anyway.

Put DataDirectory key under HKCU (prompting user for the value using folder browser if the key doesn't exist).  This ensures that each user account has a unique database, and there won't be access errors across accounts.  If you locate put the DataDirectory key as a global value in HKLM, then you'll end up with the following error case:
1. User A runs installer and writes a DataDirectory value like `C:\Users\userA\Documents\OCTGN`
2. User A runs installed program, everything works fine
3. User B runs installed program, but can't access user A's folder due to default Windows permissions (since OCTGN tries to load the DataDirectory specified in HKLM as `C:\Users\userA\Documents\OCTGN`, rather than getting the "expected" value of `C:\Users\userB\Documents\OCTGN`)

I think the fundamental fix is a fall-back at startup in octgnFX/Octgn/App.xaml.cs in case the DataDirectory key doesn't exist in HKCU; rather than shutting down the app (current behavior), prompt the user to create the key using a folder browser.  This offers full multi-user support with minimum change.

**Comment by kellyelton** [comment]
Yeah that's not a bad idea.

**Comment by kellyelton** [comment]
If you're available, can you test that this new installer solves this problem? https://github.com/octgn/OCTGN/releases/download/3.4.202.0/OCTGN-Setup-3.4.202.0.msi

**Comment by kellyelton** [comment]
Resolved with 3.4
