### ISSUE TITLE
Octgn cant join local game

### ISSUE THREAD

**Issue by johannoctum** [octgn/OCTGN#1854]
Hi
I tried to get octgn to work locally as it has done before. But i can not check in the box for local game. I can play locally with one player but i cannot play two handed, whats the issue here?

**Comment by Wirox** [comment]
On my end I have no problems joining a single local game as two separate players.
Please make sure that at least one of the following is true:
1. You do not log in on both instances of OCTGN.
2. `Options -> Basic Options -> Enable Advanced Options` setting is turned on, and when you open a lobby, you click 'Host Game on LAN'.

**Comment by BenMatteson** [comment]
also, if you have not logged in, the check box will not be visible(unless you also have advanced options on) but the game will still be hosted locally. 
let us know if that's the cause of confusion, I think the goal was to hide extra (kinda ugly) UI elements if they weren't relevant (if you're not logged in, you don't have a choice but to host locally), but it does create an absence of feedback about how the game will be hosted.

**Comment by Kwaice** [comment]
I have a similar problem.

I can't join a local game i created (to play offline two-handed) using different player names.

I used to press "Join Unlisted" then change the Player name to P2 (using P1 and P2 for clarity while ingame).
Now when i press Join Unlisted after changing the name, nothing happens.

It only lets me join by clicking the created game in the Game List.
Problem: when doing so, the players have the same name (P1 and P1). Which leads to another problem when trying to take control of the other player cards (for ease while playing two-handed), it apparently won't let me take control of cards owned by a player if he has the same name.

**Comment by kellyelton** [comment]
This should be resolved now in version 3.3.131.0 . If it isn't, let us know.
