### ISSUE TITLE
Feature Request: Allow setting the inbuilt turn counter

### ISSUE THREAD

**Issue by nitro-x** [octgn/OCTGN#1886]
To allow things like soft reset to work nicely.

**Comment by brine** [comment]
linking this to #1939

**Comment by brine** [comment]
a proper soft reset feature will be included in the next major update

(fixed in #2088)

**Comment by brine** [comment]
this will be closed as the soft reset feature fixes the root issue here.

discussion for the issue of changing the internal turn counter should continue in #1939
