### ISSUE TITLE
Notes Tab Crashes if No Deck is Loaded

### ISSUE THREAD

**Issue by zz1000zz** [octgn/OCTGN#1895]
If a player clicks on the Notes tab in the deck editor and types prior to starting a deck (either by New Deck or Load Deck), OCTGN will crash.  The tab probably shouldn't be displayed if no deck is active.

Also, the Global tab probably shouldn't appear for games which don't have a global section.  There's no use in it for such games, and it's distracting, especially now there is a count variable displayed for it.

**Comment by brine** [comment]
this should have been closed when the referenced pull request got merged
