### ISSUE TITLE
Feature request: Add isLimited parameter to OnDeckLoaded

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#2035]
Currently it's impossible to tell whether the deck loaded by a player is a regular or a limited one (i.e. made from random cards). A new boolean parameter passed by the [OnDeckLoaded](https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.2-API-Reference#ondeckloaded) event seems like the best solution to this problem.

**Comment by brine** [comment]
fixed in #2088
