### ISSUE TITLE
Ability to load multiple searches

### ISSUE THREAD

**Issue by Otep3210** [octgn/OCTGN#2051]
I would like to be able to load more than 1 search at a time, currently if I wanted to load several different searches it would need to be done 1 at a time. Being able to load 5-10 at a time would be nice when building a deck.

**Comment by brine** [comment]
just to clarify, you want to be able to select multiple search save files from a single dialog window?  Should be pretty simple to fix that up.

**Comment by Otep3210** [comment]
Correct, most of the time when building I will want to load at least 5 or 6 various searches, sometimes upwards of 15 when really brainstorming. So being able to select them all at once and load them would be great. Would then be able to group them in folders for the type of search then and just open everything in the folder.
