### ISSUE TITLE
Games hosted on the server are listed twice? (v324)

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#2081]
When you host an online game, your lobby shows up on the list twice.  It doesn't seem to matter which one you join, they both connect to the same game lobby.  Launching the game will move both of them to the spectating tab as well

**Comment by kellyelton** [comment]
I can't replicate this

**Comment by brine** [comment]
I'll check with the latest version and see if I can replicate it again

**Comment by brine** [comment]
![image](https://user-images.githubusercontent.com/1373820/99918357-48c57d80-2ce4-11eb-8e58-d9f4ebe5f0c1.png)
