### ISSUE TITLE
Uninstalling games often requires restarting OCTGN

### ISSUE THREAD

**Issue by Wirox** [octgn/OCTGN#2091]
In some situations games cannot be uninstalled until OCTGN is restarted. Attempting to uninstall results in the following error:
> Could not uninstall the game. Please try exiting all running instances of OCTGN and try again.
You can also try switching feeds, and then switching back and try again.

Steps to reproduce the issue:
1. Start OCTGN.
2. Install 'Arkham Horror - The Card Game' (the issue isn't exclusive to this game, but I haven't been able to reproduce the issue with some other games)
3. Open a lobby for Arkham Horror and start the game.
4. Leave the game.
5. Try to uninstall the game – this should result in the aforementioned error.
6. After restarting OCTGN the game can be uninstalled without problems.

**Comment by brine** [comment]
can you check the actual game database and see if any parts of the game actually got deleted during the uninstall attempt?

**Comment by brine** [comment]
I just tested this and it looks like the game board image gets locked after playing the game, giving an IOException when trying to uninstall it.
