### ISSUE TITLE
Broken drag animation in hand 

### ISSUE THREAD

**Issue by kellyelton** [octgn/OCTGN#2106]
Have 2 cards in your hand. Drag the left card to the right of the right card.

**Comment by kellyelton** [comment]
> 6:42 AM] Wirox: It doesn't happen when moving cards from right to left
> [6:48 AM] Wirox: When you drag a card from left to right on top of another card that's not a direct neighbour, that weird animation will be displayed for both cards.

**Comment by brine** [comment]
wtf when did this even start, I swear I've been doing this out of habit whenever I ran tests in the play table

**Comment by BenMatteson** [comment]
fixed by #2110
