### ISSUE TITLE
OCTGN registration issue

### ISSUE THREAD

**Issue by jasonconlon** [octgn/OCTGN#2167]
https://www.octgn.net/Account/Register
Seems to be a problem with the registration system, possibly since the update (although it could be unrelated).  When you try to register, it errors:
------------
There was an error during registration. Please wait a few minutes and try again. If the problem doesn't go away let us know.
There was an error, please try again
------------

Issue is occurring on multiple browsers, multiple PCs, for different people at different locations.  It's been a problem for at least 10 hours now.

**Comment by brine** [comment]
can you check if it's still causing issues for you

**Comment by jasonconlon** [comment]
Sorry to report that this is still an issue.  Same "There was an error during registration..." when trying to register a new OCTGN account.

**Comment by jasonconlon** [comment]
A-ha!  I have successfully completed a registration.  Here's what seems to have been the problem:

When filling in registration details, the password help text comes up saying "The Password must be at least 6 characters long." and once you've met that criteria, the help text goes away.  If you do enter a password that is only 6 characters and is all alpha characters (e.g. "abcdef"), then when you complete registration you get that generic "There was an error during registration..." error.  However, when I put in a more secure password (i.e. this time I put in a longer password with alpha, numeric and symbols) then the registration completed successfully.

So the issue seems to be that the password help text and validation needs to be updated to match whatever the current criteria now really is.

**Comment by kellyelton** [comment]
fixed
