### ISSUE TITLE
Error deck editor

### ISSUE THREAD

**Issue by Wamuuh** [octgn/OCTGN#2213]
When i try to download images in the deck editor with the plugins "image downloader" i got this

System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Le nom distant n'a pas pu être résolu: 'www.hi-izuru.org'
   à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à ImageFetcher.PluginWindow.DownloadSet(SetItem setItem, IProgress`1 progress)
   à ImageFetcher.PluginWindow.<>c__DisplayClass27_0.<Generate>b__2()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à ImageFetcher.PluginWindow.<Generate>d__27.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Exception interne #0) System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Le nom distant n'a pas pu être résolu: 'www.hi-izuru.org'
   à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---<---

**Comment by iGemini** [comment]
This is not an issue with OCTGN or the image downloader plugin (which is not a part of OCTGN either way), it's an issue with the website where the images are/were hosted.
The website it tries to get its images from seems to be dead, there's is no IP address for it.

Closing this as it is not something we can fix.
