### ISSUE TITLE
Subscribed user can't use "Save Search" feature

### ISSUE THREAD

**Issue by jrroosevelt** [octgn/OCTGN#2219]
**Describe the bug**
I am a subscribed user, but get an error when attempting to utilize the "Save Search" features in the Deck Editor.

**To Reproduce**
1. In OCTGN, click **Deck Editor**.
2. In the Deck Editor, navigate to any of the options under **Save Search.**
3. Receive an error that says:
> This feature is only for subscribers. Please visit http://www.octgn.net for subscription information.

**Expected behavior**
Because I am subscribed (verified in my account that I have a Gold subscription), I would expect to have access to these features, and did prior to the current update. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 3.4.383.0

**Comment by kellyelton** [comment]
Thanks for reporting this

**Comment by kellyelton** [comment]
This is fixed now. Let me know if this happens again.
