### ISSUE TITLE
Improved Filters in Deck Editor

### ISSUE THREAD

**Issue by Entropy42** [octgn/OCTGN#320]
Really there are a ton of ways these could be improved.  One would be some additional logic in the "Contains" search string.  Another would be better enumeration.  The game I work on (Warhammer Invasion) has 7 races, each card has a race type, and only 1 type, but I can't get a dropdown box instead of a text box for the type.  Same with "Unique" which is always Yes or No.  Sometimes I might want to search for all cards that are Race = Dwarf or Race = Neutral.  It doesn't allow you to do that (or if it does, then my feature request is some in-editor description of how to do so).  Being able to flag a property as an int type and then have the editor let you do a range would be valuable.  Such as "Attack" = > 2 && < 5.

**Comment by BenMatteson** [comment]
much of this has been added, remaining suggestions have been split into #2017 and #2018
