### ISSUE TITLE
Different back side images for certain cards

### ISSUE THREAD

**Issue by Kempeth** [octgn/OCTGN#366]
Some games have cards where the back side is different from the rest. Sometimes it's even important to the gameplay.

Examples:

* "EVE - The Second Genesis" has "Starbase" cards that start on the table on one side and can later be turned face up to show a different version
* "Summoner Wars" - Each faction has a different back side image for their cards. While it is mostly just flavor, when playing custom decks that include Mercenary cards it can be helpful for the opponent to know that such a card is coming up.

Probably the most straight forward way to implement this would be a new (optional) attribute to the card elements in the set definition that overrides the default card back image specified in the game definition.

**Comment by brine** [comment]
This should have been tagged and closed alongside the custom card sizes as you can now assign different card backs to cards
