### ISSUE TITLE
Reveal X cards and show to X players

### ISSUE THREAD

**Issue by ralig** [octgn/OCTGN#39]
From Entropy: I just remembered a deficiency in OCTGN that I would like to see changed in O3.  In Warhammer, there are many cards that say "reveal the top 5 cards of your deck and choose XXX"  But there is no way to reveal 5 cards in OCTGN, other than just drawing them all and putting them on the table.  Would be nice to have that "Look at top X cards" pop up window be visible to both players

**Comment by brine** [comment]
Now that python can read properties of hidden cards, this functionality can be replicated by printing the names of the cards in a notify message, then using askCard to select the card.
