### ISSUE TITLE
Convert to Mono

### ISSUE THREAD

**Issue by robertmeta** [octgn/OCTGN#55]
Various parts of the application are not currently cross-platform.  We use registry, WPF, and other bits.  We need to research what it would take to get it all to work cross-platform.

**Comment by kellyelton** [comment]
![image](https://media.giphy.com/media/3oEduQgyEr6wev9c3K/giphy.gif)

**Comment by kellyelton** [comment]
See Also:

![image](http://i1058.photobucket.com/albums/t414/Hungryeric/shots-fired-o.gif)
