### ISSUE TITLE
Add Function for creating new chatrooms?

### ISSUE THREAD

**Issue by XxPriestxX** [octgn/OCTGN#748]
Haven't been able to find it and all I can get into is the lobby.  Would like to be able to setup chatrooms for the specific games.  Specifically MTG.  Going to be pushing for this program to be used in a league type setting.  Working on a rating / tourney system.  OCTGN >MWS.  MWS is old, boring, and outdated.  Going to do my best to get this program involved in a league for MTG.

**Comment by brine** [comment]
mcbeth just shed a tear
