### ISSUE TITLE
Alternates and the deck editor

### ISSUE THREAD

**Issue by kellyelton** [octgn/OCTGN#793]
brine
> Deck editor needs a method to view all alternate modes. Before, you could click the card's image in the editor to toggle to a different image. Maybe this is good enough?

> Deck editor needs to show the properties of the alternate modes. Dunno how to do this, maybe have a new row spawn under the original mode's row. Maybe have like a + button to expand to sub-rows? It may be weird depending on how the deck editor displays the card data. Maybe just clicking any cell in the row could hot-swap all the properties to an alternate (cycles/toggles between them).

**Comment by brine** [comment]
card alternates show up as though they were regular cards in the deck editor.  good enough i think
