### ISSUE TITLE
game XML element - lock players from manually drag/moving cards

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#800]
A new element in the <game> tag which can globally disable the manual movement of cards on the table.

Something like lockCardMovement="True", defaults to "False" if the element is missing.

Having this enabled would allow games with higher-order automation to keep the cards organized on the table without the potential for players to move the cards around on their own.  It would also prevent players from manually moving cards to other piles, which could have a negative impact on a game's automations.

**Comment by torrentails** [comment]
I realise this is old but I feel that this would be a most beneficial feature. If a designer is smart about it, there should be no need for their players to move cards around manually.  
Just imagine if Hearthstone or Infinity Wars said "Well, the entire game and it's card movement is automated, but if you really want to, we'll let you move cards around manually." It would completely break the game, so why shouldn't designers have the same level of control here?

Look at it another way, if we make a highly automated game, most players are going to use said automation; those who don't, likely don't understand that the game is automated or they are trying to cheat, in either case, enforcement and a polite message will be the best reminder, .

**Comment by brine** [comment]
MoveCard overrides properly handles this
