### ISSUE TITLE
.net 4.0 memory fix on win xp

### ISSUE THREAD

**Issue by Gravecorp** [octgn/OCTGN#823]
http://www.microsoft.com/en-us/download/details.aspx?id=29053
Installing that for your specific architecture ie x86 x64 ia64 will fix the memory problems on windows xp.
Can someone put that into the installer for the windows xp specific bit?

**Comment by Soul1355** [comment]
do we still have an XP specific anything? maybe it should be stripping that out instead at this point...

**Comment by brine** [comment]
closed as windows XP is dumpstered
