### ISSUE TITLE
In-game 'deck window' unable to close due to misplaced window+bar being out-of-screen

### ISSUE THREAD

**Issue by grifcha** [octgn/OCTGN#844]
Hi peeps.

This happens to me pretty often: When I open the in-game 'deck' window (e.g. look at all cards), the window cannot be closed. This is because the window-bar, which hosts the close (x) button, finds itself above the viewable area. There are no alternative ways to close this virtual window, nor are the window's border's dragable.

Here are more deets:

-Running a standard netbook
-I've only played ANR

Here are some potential fixes:
- have a right-click close option (either on the window itself or on the deck)
- make window dragable.

Thanks for all your hard work, you amazing wizards!

![image](https://f.cloud.github.com/assets/4413399/494001/a254e5dc-bb7e-11e2-9a8b-282d73376b8e.png)

**Comment by Soul1355** [comment]
I believe we fixed this, let us know if this is not true.
