### ISSUE TITLE
Provide an API to the turn pause

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#951]
When you're a non-active player, the play button of the other player's tab becomes a pause. I'd like an API to be able to set this to pause/resume via python and also to be able to poll that state as a boolean. 

Then I can use this in a custom button which will also block all script execution for the opponent until the turn is resumed.

**Comment by brine** [comment]
just running through some old tickets, I believe we added this in with the game phases update (getStop and setStop API)
